name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present

  
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest


    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest
          docker stop ecommerce-frontend || true
          docker rm ecommerce-frontend || true
          docker run -d \
            --name ecommerce-frontend \
            --restart always \
            -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest
